version: '0.1.0'

services:
  node_1:
    image: ghcr.io/redactedfury/fury:main
    ports:
      - '26656:26656'
      - '26657:26657'
      - '1317:1317'
    environment:
      - MONIKER=redshift
      - CHAIN_JSON=https://github.com/redactedfury/fury/blob/main/chain.json
    volumes:
      - ./node-data:/root/.fury